### ISSUE TITLE
Data storage options for file content and metadata

### ISSUE THREAD

**Issue by beverloo** [GoogleChromeLabs/llaminator#21]
For each file stored in Llaminator, we'll have _(a)_ the file's contents, and _(b)_ metadata about the file, e.g. its name and description. We need to decide on how this storage layer is going to work.

**Requirements**
- Storage in our control (i.e. not the browser cache) in which we can get, set and delete arbitrary data.
- The storage should strictly live on the user's device, and not be synchronized.
- We should be able to read metadata without reading file contents.

Improved developer experience over IndexedDB would also be grand, where a library such as [IDB](https://github.com/jakearchibald/idb) would get us quite far already.

**Comment by beverloo** [comment]
To sketch out a potential (& excessive) interface:

```typescript
type FileUniqueID = string;  // generated by the storage layer
type FileMetadata = {
  added: number;  // timestamp
  filename: string;
  title?: string;
}

type FileRecord = { id: FileUniqueID; metadata: FileMetadata; }; 

interface LlamaStorage {
  async add(file: Blob, metadata: FileMetadata): Promise<FileUniqueID>;

  async list(): Promise<FileRecord[]>;

  async getFile(id: FileUniqueID): Promise<Blob>;
  async get(id: FileUniqueID): Promise<FileMetadata>;

  async updateFile(id: FileUniqueID, file: Blob): Promise<void>;
  async update(id: FileUniqueID, metadata: FileMetadata): Promise<void>;

  async delete(id: FileUniqueID): Promise<void>;
}
```

**Comment by glennhartmann** [comment]
A few small things:

* maybe we should keep a mime type in `FileMetadata` as well, though it may be deducible from the extension in `filename`
* `added` (the timestamp) might work better as part of `FileRecord` - it would be nice for the `add` and `update` functions to deal with that rather than the caller. (Do we also need a `modified`?)
* perhaps `add` and `get` should return `FileRecord`
* I imagine we'll generally want to update the blob and metadata at the same time. Might be easier to have a single `update` function? We could make the args nullable in case we ever need to update just one at a time.

**Comment by beverloo** [comment]
Do you want to pick this up @glennhartmann, or shall I?

**Comment by glennhartmann** [comment]
I'll take it - I haven't made any "real changes" in a while

**Comment by glennhartmann** [comment]
Keeping this open until random unique IDs are implemented
