### ISSUE TITLE
set up TypeScript and build system

### ISSUE THREAD

**Issue by glennhartmann** [GoogleChromeLabs/llaminator#4]

**Comment by beverloo** [comment]
We can use [@web/dev-server](https://www.npmjs.com/package/@web/dev-server) for the serving environment. Not much functionality is needed because we're a client-side app, but it's not clear whether we could cleanly integrate TypeScript support with something like [superstatic](https://www.npmjs.com/package/superstatic).

We then have a few options -

If we're interested in using JSX (with whichever factory), something like [esbuild](https://www.npmjs.com/package/esbuild) would work well. That also goes if we'd like to use any of its plugins (e.g. for minimization) or loaders.

A more bareboned solution would be to directly use the [TypeScript](https://www.npmjs.com/package/typescript) compiler, possibly with use of [concurrently](https://www.npmjs.com/package/concurrently) to make support cross-platform. I use Windows, after all.

With both solutions we'd get watch + live refresh functionality, making for quite a nice development environment. The `esbuild` solution will likely be more future proof, particularly if we'd like the result to be minimized.

**Comment by glennhartmann** [comment]
> We can use [@web/dev-server](https://www.npmjs.com/package/@web/dev-server) for the serving environment. Not much functionality is needed because we're a client-side app, but it's not clear whether we could cleanly integrate TypeScript support with something like [superstatic](https://www.npmjs.com/package/superstatic).

We might not want to restrict ourselves to static-only anyway, in case we end up wanting to implement cross-device sync of some sort.

> With both solutions we'd get watch + live refresh functionality, making for quite a nice development environment. The `esbuild` solution will likely be more future proof, particularly if we'd like the result to be minimized.

SGTM. Not sure how important minimizing will be, but at least we have the option.
